/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force reload bulk data */
        post: operations["admin_reload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/named": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a card by name (fuzzy or exact) */
        get: operations["get_card_by_name"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for cards */
        get: operations["search_cards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific card by ID */
        get: operations["get_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cache statistics */
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Cache statistics */
        CacheStats: {
            /**
             * Format: int64
             * @description Total number of cached query results
             */
            total_cache_entries: number;
            /**
             * Format: int64
             * @description Total number of cards in the database
             */
            total_cards: number;
        };
        /** @description A Magic: The Gathering card from the Scryfall database */
        Card: {
            card_faces?: unknown;
            /** Format: double */
            cmc?: number | null;
            collector_number?: string | null;
            color_identity?: string[] | null;
            colors?: string[] | null;
            /** Format: uuid */
            id: string;
            image_uris?: unknown;
            keywords?: string[] | null;
            legalities?: unknown;
            loyalty?: string | null;
            mana_cost?: string | null;
            name: string;
            /** Format: uuid */
            oracle_id?: string | null;
            oracle_text?: string | null;
            power?: string | null;
            prices?: unknown;
            rarity?: string | null;
            raw_json: unknown;
            /** Format: date */
            released_at?: string | null;
            set_code?: string | null;
            set_name?: string | null;
            toughness?: string | null;
            type_line?: string | null;
        };
        /** @description Paginated card list response */
        CardListResponse: {
            data?: components["schemas"]["PaginatedCardData"] | null;
            /** @description Error message (present if success is false) */
            error?: string | null;
            /** @description Whether the request was successful */
            success: boolean;
        };
        /** @description Card response */
        CardResponse: {
            data?: components["schemas"]["Card"] | null;
            /** @description Error message (present if success is false) */
            error?: string | null;
            /** @description Whether the request was successful */
            success: boolean;
        };
        /** @description Named card lookup parameters */
        NamedParams: {
            /** @description Exact card name search (case-insensitive) */
            exact?: string | null;
            /** @description Fuzzy card name search (e.g., "light bolt" matches "Lightning Bolt") */
            fuzzy?: string | null;
        };
        /** @description Paginated card data */
        PaginatedCardData: {
            /** @description Array of results for the current page */
            data: components["schemas"]["Card"][];
            /** @description Whether there are more pages available */
            has_more: boolean;
            /** @description Current page number */
            page: number;
            /** @description Number of results per page */
            page_size: number;
            /** @description Total number of results across all pages */
            total: number;
            /** @description Total number of pages */
            total_pages: number;
        };
        /** @description Reload response */
        ReloadResponse: {
            /** @description Response data (present if success is true) */
            data?: string | null;
            /** @description Error message (present if success is false) */
            error?: string | null;
            /** @description Whether the request was successful */
            success: boolean;
        };
        /** @description Search query parameters */
        SearchParams: {
            /**
             * Format: int64
             * @description Maximum number of results to return (default: unlimited)
             */
            limit?: number | null;
            /** @description Page number for pagination (starts at 1) */
            page?: number | null;
            /** @description Number of results per page (default: 100, max: 1000) */
            page_size?: number | null;
            /** @description Scryfall search query (e.g., "c:red cmc:1" or "Sol Ring") */
            q: string;
        };
        /** @description Cache statistics response */
        StatsResponse: {
            data?: components["schemas"]["CacheStats"] | null;
            /** @description Error message (present if success is false) */
            error?: string | null;
            /** @description Whether the request was successful */
            success: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_reload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bulk data reload completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadResponse"];
                };
            };
            /** @description Reload failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadResponse"];
                };
            };
        };
    };
    get_card_by_name: {
        parameters: {
            query?: {
                /** @description Fuzzy card name search (e.g., "light bolt" matches "Lightning Bolt") */
                fuzzy?: string | null;
                /** @description Exact card name search (case-insensitive) */
                exact?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Bad request - must provide fuzzy or exact parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
        };
    };
    search_cards: {
        parameters: {
            query: {
                /** @description Scryfall search query (e.g., "c:red cmc:1" or "Sol Ring") */
                q: string;
                /** @description Maximum number of results to return (default: unlimited) */
                limit?: number | null;
                /** @description Page number for pagination (starts at 1) */
                page?: number | null;
                /** @description Number of results per page (default: 100, max: 1000) */
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListResponse"];
                };
            };
        };
    };
    get_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
}
